export const themes = {
  light: {
    background: "#ffffff",
    backgroundSecondary: "#FCFCFC",
    text: "#161616",
    primary: "#BEDBB0",
    secondaryText: "#16161680",
    accent: "#BEDBB0",
    labelHighPriority: "#BEDBB0",
    labelMediumPriroity: "#E09CB5",
    labelLowPriority: "#8FA1D0",
    labelWithoutPriority: "#1616164D",
  },
  dark: {
    background: "#1F1F1F",
    backgroundSecondary: "#161616",
    text: "#ffffff",
    primary: "#BEDBB0",
    secondaryText: "#FFFFFF80",
    accent: "#BEDBB0",
    labelHighPriority: "#BEDBB0",
    labelMediumPriroity: "#E09CB5",
    labelLowPriority: "#8FA1D0",
    labelWithoutPriority: "#1616164D",
  },
  violet: {
    background: "#ECEDFD",
    backgroundSecondary: "#FCFCFC",
    text: "#161616",
    primary: "#5255BC",
    secondaryText: "#161616B2",
    accent: "#ECEDFD66",
    labelHighPriority: "#BEDBB0",
    labelMediumPriroity: "#E09CB5",
    labelLowPriority: "#8FA1D0",
    labelWithoutPriority: "#1616164D",
  },
};
