export const themes = {
  light: {
    background: "#ffffff",
    backgroundSecondary: "#FCFCFC",
    sidebar: "#fff",
    icon: "#1F1F1F",
    logo: "#1F1F1F",
    hoverColor: "#9dc888",
    buttonText: "#161616",
    text: "#161616",
    primary: "#BEDBB0",
    secondaryText: "#16161680",
    accent: "#BEDBB0",
    labelHighPriority: "#BEDBB0",
    labelMediumPriroity: "#E09CB5",
    labelLowPriority: "#8FA1D0",
    labelWithoutPriority: "#1616164D",
  },
  dark: {
    background: "#1F1F1F",
    backgroundSecondary: "#161616",
    sidebar: "#121212",
    icon: "#1F1F1F",
    logo: "#ffffff",
    hoverColor: "#9dc888",
    buttonText: "#161616",
    text: "#ffffff",
    primary: "#BEDBB0",
    secondaryText: "#FFFFFF80",
    accent: "#BEDBB0",
    labelHighPriority: "#BEDBB0",
    labelMediumPriroity: "#E09CB5",
    labelLowPriority: "#8FA1D0",
    labelWithoutPriority: "#1616164D",
  },
  violet: {
    background: "#ECEDFD",
    backgroundSecondary: "#FCFCFC",
    sidebar: "#5255BC",
    icon: "#ECEDFD",
    logo: "#fff",
    buttonText: "#FCFCFC",
    hoverColor: "#7B7EDE",
    text: "#161616",
    primary: "#5255BC",
    secondaryText: "#FFFFFF",
    accent: "#B8BCFD",
    labelHighPriority: "#BEDBB0",
    labelMediumPriroity: "#E09CB5",
    labelLowPriority: "#8FA1D0",
    labelWithoutPriority: "#1616164D",
  },
};
